---
- name: Pull Docker Image of HelloWorld Python program
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: iiitb/mytestimage
        source: pull
    - name: Start Docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name HelloWorld iiitb/mytestimage
