---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: abhishekrauthan
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "abhishekrauthan2023106/calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Start Docker service
      service:
       name: docker
       state: started
      when: ansible_facts['os_family'] == "Debian"
      
    - name: Running container
      shell: docker run -it -d --name calculator calculator
      when: ansible_facts['os_family'] == "Debian"

